
class WorkflowStatus:
    ACTIVE = 'ACTIVE'
    COMPLETED = 'COMPLETED'
    FAILED = 'FAILED'
    CANCELED = 'CANCELED'
    TERMINATED = 'TERMINATED'
    CONTINUED_AS_NEW = 'CONTINUED_AS_NEW'
    TIMED_OUT = 'TIMED_OUT'


class RegistrationStatus:
    REGISTERED = 'REGISTERED'
    DEPRECATED = 'DEPRECATED'
